# Generated by Django 3.1.2 on 2020-10-04 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSQI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 10, 3))),
                ('latencyGreaterThan30', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('midnightAwakeEarlyMorning', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('useBathroom', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('uncomfortableBreathing', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('coughSnore', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('feelCold', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('feelHot', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('badDreams', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('pain', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('otherReason', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('sleepMedication', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('stayAwakeDuringWork', models.CharField(choices=[('0', 'notDuringPastMonth'), ('1', 'lessThanOnceAWeek'), ('2', 'onceTwiceAWeek'), ('3', 'greaterThan3Aweek')], default='1', max_length=20)),
                ('enthusiasmToDoThings', models.CharField(choices=[('0', 'noProblem'), ('1', 'slightProblem'), ('2', 'someWhatAProblem'), ('3', 'bigProblem')], default='1', max_length=20)),
                ('selfRatedSleepQuality', models.CharField(choices=[('0', 'VeryGood'), ('1', 'FairlyGood'), ('2', 'FairlyBad'), ('3', 'VeryBad')], default='1', max_length=20)),
            ],
        ),
    ]
