# Generated by Django 3.1.2 on 2020-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSQI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latencyGreaterThan30', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('midnightAwakeEarlyMorning', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('useBathroom', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('uncomfortableBreathing', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('coughSnore', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('feelCold', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('feelHot', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('badDreams', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('pain', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('otherReason', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('sleepMedication', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('stayAwakeDuringWork', models.CharField(choices=[('notDuringPastMonth', '0'), ('lessThanOnceAWeek', '1'), ('onceTwiceAWeek', '2'), ('greaterThan3Aweek', '3')], default='1', max_length=20)),
                ('enthusiasmToDoThings', models.CharField(choices=[('noProblem', '0'), ('slightProblem', '1'), ('someWhatAProblem', '2'), ('bigProblem', '3')], default='1', max_length=20)),
                ('selfRatedSleepQuality', models.CharField(choices=[('Very Good', '0'), ('Fairly Good', '1'), ('Fairly Bad', '2'), ('Very Bad', '3')], default='1', max_length=20)),
            ],
        ),
    ]
