# Generated by Django 3.1.2 on 2020-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSQI', '0002_psqi_userfeedbackintensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='psqi',
            name='day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
