# Generated by Django 3.1.2 on 2020-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSQI', '0002_auto_20201003_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='psqi',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
