# Generated by Django 3.1.2 on 2020-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0002_auto_20201004_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
