# Generated by Django 3.1.2 on 2020-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_sleep_time', models.IntegerField()),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('latency', models.IntegerField()),
                ('body_temperature', models.IntegerField()),
                ('restfulness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('REM', models.DecimalField(decimal_places=2, max_digits=3)),
                ('deep_sleep', models.DecimalField(decimal_places=2, max_digits=3)),
                ('average_resting_heart_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sleep_helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nap_start', models.DateTimeField()),
                ('nap_end', models.DateTimeField()),
                ('light', models.DecimalField(decimal_places=2, max_digits=3)),
                ('caffeine', models.BooleanField(default=False)),
                ('melatonin', models.BooleanField(default=False)),
            ],
        ),
    ]
