# Generated by Django 3.1.2 on 2020-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(),
        ),
    ]
