# Generated by Django 3.1.2 on 2020-10-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0004_auto_20201003_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='REM',
            new_name='deep',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='average_resting_heart_rate',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='deep_sleep',
            new_name='rem',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='total_sleep_time',
            new_name='resting_heart_rate',
        ),
    ]
