# Generated by Django 3.1.2 on 2020-10-04 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0008_auto_20201003_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='body_temperature',
            field=models.IntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='deep',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='duration',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='latency',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='rem',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='restfulness',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='resting_heart_rate',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
    ]
