# Generated by Django 3.1.2 on 2020-10-04 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astronauts', '0003_auto_20201004_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(23, 0))),
                ('end_time', models.TimeField(default=datetime.time(8, 0))),
                ('take_meditation', models.BooleanField(blank=True, default=False, null=True)),
                ('take_melatonin', models.BooleanField(blank=True, default=False, null=True)),
                ('take_caffeine', models.BooleanField(blank=True, default=False, null=True)),
                ('take_nap', models.BooleanField(blank=True, default=False, null=True)),
                ('nap_start', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('nap_end', models.TimeField(blank=True, default=datetime.time(15, 0), null=True)),
                ('resistant_excercise_start', models.TimeField(blank=True, default=datetime.time(15, 0), null=True)),
                ('resistant_excercise_end', models.TimeField(blank=True, default=datetime.time(15, 30), null=True)),
                ('aerobics_exercise_start', models.TimeField(blank=True, default=datetime.time(15, 30), null=True)),
                ('aerobics_exercise_end', models.TimeField(blank=True, default=datetime.time(16, 0), null=True)),
                ('breakfast_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('breakfast_end_time', models.TimeField(default=datetime.time(8, 15))),
                ('lunch_start_time', models.TimeField(default=datetime.time(12, 0))),
                ('lunch_end_time', models.TimeField(default=datetime.time(12, 30))),
                ('dinner_start_time', models.TimeField(default=datetime.time(18, 0))),
                ('dinner_end_time', models.TimeField(default=datetime.time(19, 0))),
                ('sensed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('PSQI_score', models.IntegerField(blank=True, null=True)),
                ('light_work_hrs', models.DecimalField(decimal_places=2, default=4, max_digits=3)),
                ('heavy_work_hrs', models.DecimalField(decimal_places=2, default=4, max_digits=3)),
                ('astronaut', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='astronauts.astronaut')),
            ],
        ),
    ]
