# Generated by Django 3.1.2 on 2020-10-04 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 0), null=True),
        ),
    ]
