# Generated by Django 3.1.2 on 2020-10-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
