# Generated by Django 3.1.2 on 2020-10-03 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20201003_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
