# Generated by Django 3.1.2 on 2020-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201003_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='nap_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='nap_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
