# Generated by Django 3.1.2 on 2020-10-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201004_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep_schedule',
            old_name='do_excercise',
            new_name='do_aerobics',
        ),
        migrations.AddField(
            model_name='sleep_schedule',
            name='do_resistant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
