# Generated by Django 3.1.2 on 2020-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201003_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
