# Generated by Django 3.1.2 on 2020-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201004_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep_schedule',
            name='day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
