# Generated by Django 3.1.2 on 2020-10-03 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20201003_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='breakfast_end_time',
            field=models.TimeField(default=datetime.time(8, 15)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='breakfast_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='dinner_end_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='dinner_start_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='lunch_end_time',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='lunch_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.time(23, 0)),
        ),
    ]
