# Generated by Django 3.1.2 on 2020-10-03 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20201003_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep_schedule',
            old_name='excercise_end',
            new_name='aerobics_exercise_end',
        ),
        migrations.RenameField(
            model_name='sleep_schedule',
            old_name='exercise_start',
            new_name='aerobics_exercise_start',
        ),
        migrations.RemoveField(
            model_name='sleep_schedule',
            name='excercise_type',
        ),
        migrations.AddField(
            model_name='sleep_schedule',
            name='resistant_excercise_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleep_schedule',
            name='resistant_excercise_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
    ]
