# Generated by Django 3.1.2 on 2020-10-04 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20201003_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep_schedule',
            name='caffeine',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sleep_schedule',
            name='melatonin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sleep_schedule',
            name='take_nap',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='aerobics_exercise_end',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='aerobics_exercise_start',
            field=models.TimeField(blank=True, default=datetime.time(15, 30), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='nap_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='nap_start',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='resistant_excercise_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 30), null=True),
        ),
        migrations.AlterField(
            model_name='sleep_schedule',
            name='resistant_excercise_start',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
    ]
