# Generated by Django 3.1.2 on 2020-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20201004_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep_schedule',
            name='sensed_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
