# Generated by Django 3.1.2 on 2020-10-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('userFeedBackIntensity', models.IntegerField(default=6)),
                ('lastTargetIntensity', models.FloatField(default=0)),
                ('targetIntensity', models.FloatField(default=7)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('aredTime', models.FloatField(blank=True, null=True)),
                ('aerobicTime', models.FloatField(blank=True, null=True)),
                ('load', models.FloatField(blank=True, null=True)),
                # ('PSQI', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PSQI.psqi')),
            ],
        ),
    ]

    # initial = True

    # dependencies = [
    #     ('PSQI', '__first__'),
    # ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Exercise',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('exercise_type', models.CharField(max_length=200)),
    #             ('date', models.DateField()),
    #             ('userFeedBackIntensity', models.IntegerField(default=6)),
    #             ('lastTargetIntensity', models.FloatField(default=0)),
    #             ('targetIntensity', models.FloatField(default=7)),
    #             ('intensity', models.FloatField(blank=True, null=True)),
    #             ('aredTime', models.FloatField(blank=True, null=True)),
    #             ('aerobicTime', models.FloatField(blank=True, null=True)),
    #             ('load', models.FloatField(blank=True, null=True)),
    #             ('PSQI', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PSQI.psqi')),
    #         ],
    #     ),
    # ]
