# Generated by Django 3.1.2 on 2020-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_psqi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_type',
            new_name='aero_name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ared_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='do_exercise',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
