# Generated by Django 3.1.2 on 2020-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20201004_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='aero_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ared_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
